waypoints:
    - point:
        x: 18.6965
        y: 41.0993
        z: 0
    - point:
        x: 4.5435
        y: 41.0993
        z: 0
    - point:
        x: -5.1435
        y: 41.0993
        z: 0
    - point:
        x: -19.2965
        y: 41.0993
        z: 0
