waypoints:
- point: {x: 9.46913, y: 0.529765, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 14.9492, y: 0.871575, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 19.6856, y: 0.632644, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 24.9351, y: 0.233624, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 28.0122, y: -0.0124286, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 32.0594, y: -0.17328, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 35.7966, y: -0.423632, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 39.5993, y: -0.453472, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 43.7265, y: -1.00715, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 46.9868, y: -1.03966, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 50.4449, y: -1.17954, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 54.2481, y: -1.22557, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 57.7555, y: -1.21769, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 62.8625, y: -1.11575, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 66.7316, y: -1.22341, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 71.0413, y: -1.23109, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 75.7319, y: -1.16161, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 79.8398, y: -1.10049, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 83.0448, y: -1.1651, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 88.495, y: -0.986142, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 92.5278, y: -1.03608, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 96.6576, y: -0.955216, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 103.025, y: -0.811471, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 109.671, y: -1.51092, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 113.289, y: -2.87296, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 117.055, y: -6.03892, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 121.485, y: -8.93011, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 127.634, y: -9.38217, z: 0, vel: 1, rad: 0.8, stop: false}
finish_pose:
  header: {seq: 0, stamp: 1666500880.699932195, frame_id: map}
  pose: 
    position: {x: 127.665, y: -9.34744, z: 0}
    orientation: {x: 0, y: 0, z: -0.0112674, w: 0.999937}
