waypoints:
- point: {x: 9.77702, y: -9.35124, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 11.0658, y: -15.3721, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 12.2397, y: -21.8151, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 12.841, y: -28.787, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 13.5362, y: -34.6672, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 14.3203, y: -39.4139, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 14.8336, y: -42.912, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 16.0212, y: -50.3347, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 16.6069, y: -55.1182, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 17.7161, y: -62.4678, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 18.7441, y: -68.329, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 20.1344, y: -77.0584, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 21.1453, y: -82.7435, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 19.4133, y: -87.5299, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 20.4862, y: -95.2313, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 21.2146, y: -99.9, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 22.0481, y: -106.871, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 23.0157, y: -113.055, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 24.3563, y: -122.811, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 25.7573, y: -128.975, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 26.3403, y: -132.192, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 28.631, y: -143.115, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 30.081, y: -151.275, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 30.999, y: -156.742, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 32.6453, y: -165.493, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 33.3496, y: -169.194, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 33.9911, y: -173.797, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 36.1009, y: -183.85, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 37.9232, y: -191.819, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 39.1094, y: -199.932, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 40.4152, y: -207.271, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 41.3608, y: -213.691, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 42.1209, y: -216.883, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 42.5918, y: -220.04, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 42.6284, y: -223.072, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 43.2545, y: -226.003, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 44.2281, y: -230.068, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 45.8753, y: -234.581, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 47.2838, y: -239.107, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 47.2662, y: -243.955, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 48.0188, y: -248.266, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 48.8606, y: -253.776, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 50.5381, y: -258.264, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 51.8096, y: -261.134, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 52.6463, y: -265.871, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 52.221, y: -270.229, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 48.8503, y: -271.519, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 43.8426, y: -272.184, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 39.2682, y: -273.269, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 35.2283, y: -273.832, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 30.6588, y: -274.219, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 26.9984, y: -273.45, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 25.1512, y: -269.419, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 24.1466, y: -264.346, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 24.386, y: -257.993, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 20.2687, y: -252.105, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 19.0443, y: -245.94, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 17.9814, y: -240.87, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 16.776, y: -234.487, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 15.7553, y: -227.874, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 14.1257, y: -220.482, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 13.0743, y: -215.375, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 11.755, y: -209.173, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 10.5923, y: -204.519, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 9.87295, y: -198.553, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 9.11476, y: -194.507, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 8.91155, y: -191.779, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 7.20587, y: -185.409, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 5.90841, y: -179.699, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 4.12515, y: -172.833, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 3.1091, y: -168.22, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 2.38034, y: -163.933, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 1.38153, y: -159.197, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 0.119742, y: -153.103, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -0.393062, y: -149.66, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -1.18737, y: -145.401, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -1.86761, y: -142.314, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -2.30478, y: -137.676, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -1.78932, y: -134.716, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -4.34085, y: -131.96, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -12.8035, y: -132.725, z: 0, vel: 1, rad: 0.8, stop: false}
finish_pose:
  header: {seq: 0, stamp: 1666496150.059657956, frame_id: map}
  pose: 
    position: {x: -19.9693, y: -132.988, z: 0}
    orientation: {x: 0, y: 0, z: -0.999956, w: 0.00936597}
