waypoints:
- point: {x: 4.09724, y: 0.504168, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 16.659, y: 1.14789, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 20.5776, y: 1.30268, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 28.2563, y: 1.64634, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 38.1161, y: 1.91456, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 48.2937, y: 1.73542, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 55.5451, y: 1.66404, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 58.0735, y: 0.128874, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 61.313, y: -6.31239, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 64.9454, y: -14.2518, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 67.6144, y: -15.4014, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 70.316, y: -15.5441, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 74.2391, y: -15.3596, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 77.357, y: -15.2531, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 79.101358, y: -15.32212, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 80.470272, y: -16.227709, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 81.691765, y: -17.449202, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 83.0514, y: -18.1883, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 85.4238, y: -18.5438, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 87.9159, y: -17.5321, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 88.2617, y: -15.0813, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 88.16, y: -10.9362, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 88.0087, y: -6.39951, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 87.8094, y: -2.38376, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 87.683, y: 3.18917, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 84.1737, y: 4.69392, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 80.0329, y: 4.54753, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 74.1995, y: 2.24651, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 69.9941, y: -0.0748514, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 63.1423, y: -4.43719, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 59.449401, y: -7.597903, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 55.4954, y: -9.77409, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 51.7554, y: -10.206, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 48.1474, y: -10.3002, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 46.051, y: -11.3614, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 42.5089, y: -11.9516, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 37.4443, y: -12.0861, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 35.2285, y: -12.1586, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 33.8879, y: -14.2313, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 33.7788, y: -17.3731, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 32.519273, y: -19.091731, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 28.243205, y: -19.061404, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 23.785178, y: -19.00075, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 21.2425, y: -18.9706, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 19.1694, y: -19.0082, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 17.5523, y: -18.9316, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 15.426, y: -18.7627, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 12.495, y: -18.5628, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 10.0156, y: -18.6638, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 7.32172, y: -18.6572, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 6.06788, y: -21.9222, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 5.40629, y: -26.6174, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 0.550092, y: -27.6913, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -5.94073, y: -28.0941, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -10.5427, y: -28.3094, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -16.6638, y: -28.2209, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -23.255, y: -28.019, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -34.563433, y: -33.284636, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -43.9865, y: -35.5365, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -49.5035, y: -37.0547, z: 0, vel: 1, rad: 0.8, stop: false}
finish_pose:
  header: {seq: 0, stamp: 1666489211.5504568, frame_id: map}
  pose:
    position: {x: -59.2588, y: -38.328, z: 0}
    orientation: {x: 0, y: 0, z: -0.999995, w: 0.00302894}