waypoints:
- point: {x: 9.67825, y: 0.140065, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 17.3371, y: 0.964738, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 22.2638, y: 1.19774, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 25.6939, y: 1.36643, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 29.2721, y: 1.63943, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 33.1001, y: 1.66546, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 37.392, y: 1.57617, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 42.2553, y: 1.78286, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 46.1511, y: 1.94883, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 50.6625, y: 2.52083, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 54.483, y: 3.18138, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 61.0413, y: 4.44718, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 65.8479, y: 5.15023, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 72.7584, y: 6.25933, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 76.4122, y: 6.60277, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 80.9786, y: 6.91495, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 84.9715, y: 7.33446, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 88.3644, y: 7.20248, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 91.8132, y: 7.2966, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 96.4995, y: 7.06355, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 100.587, y: 6.83167, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 105.284, y: 7.29065, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 109.932, y: 6.8314, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 115.424, y: 7.17386, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 120.288, y: 8.25665, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 125.027, y: 8.92041, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 130.261, y: 9.92347, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 134.854, y: 10.9632, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 138.074, y: 11.7053, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 142.746, y: 12.4801, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 149.677, y: 10.0145, z: 0, vel: 1, rad: 0.8, stop: false}
finish_pose:
  header: {seq: 0, stamp: 1666498137.866959073, frame_id: map}
  pose: 
    position: {x: 151.792, y: 5.67301, z: 0}
    orientation: {x: 0, y: 0, z: -0.714715, w: 0.699416}
